### ISSUE TITLE
Imatge de portada que no surti tallada mobile

### ISSUE THREAD

**Issue by paarals** [Platoniq/decidim-coactuem#19]
Surt tallada al mbil ¿es pot arreglar?
![imatge](https://user-images.githubusercontent.com/40388743/135447067-ac3cd1ac-999c-4367-a6d6-cd7b9ac6f3e2.png)

**Comment by martanducas** [comment]
He centrat la imatge i he posat que la mida sigui "cover", és a dir, que cobreixi tota l'àrea. Així va bé?

Per altra banda, recomanaria canviar l'ordre d'elements a la home pq tal com està ara em sembla que queda molt atapeït. La meva proposta es:
- Imatge del hero
- Fases de recerca destacades
- Banner de contingut destacat

La combinació de blocs amb una imatge de fons i blocs amb fons transparent dóna aire a la portada.

**Comment by paarals** [comment]
Perfect Marta!! està genial, moltes gràcies. 
T'agafo la proposta :)
