### ISSUE TITLE
Si cliques participa, que et porti al verificador i tornes a l'assemblea

### ISSUE THREAD

**Issue by paarals** [Platoniq/decidim-coactuem#20]
Quan cliques a participa/títol assemblea de: Entorn de coneixement/Persones coinvestigadores
![imatge](https://user-images.githubusercontent.com/40388743/135447282-80f17c36-7e9b-43ed-b3b0-2c2f254177fb.png)
T'hauria de dirigir a aquesta pàgina
https://coactuem.ub.edu/tos_verification/
I tornar a la pàgina de l'assemblea

Així, tothom es verificarà abans de participar

**Comment by microstudi** [comment]
Done via  #23
