### ISSUE TITLE
Treure referència i incrustar del detall dels processos/assemblees

### ISSUE THREAD

**Issue by paarals** [Platoniq/decidim-coactuem#21]
S'ha d'eliminar via css el següent:

- [ ] Referència
- [ ] Incrusta
![imatge](https://user-images.githubusercontent.com/40388743/135447532-40bc6c81-ffbf-42a9-9ceb-ce4504e1d192.png)
link: coactuem.ub.edu/

**Comment by martanducas** [comment]
Done! Per porcessos i assamblees:

![image](https://user-images.githubusercontent.com/72607737/135824371-4037604e-f3cb-4480-8e02-a417e6cf5d6a.png)

Tb he arreglat un enllaç que donava error a https://coactuem.ub.edu/processes/xatbot > Entra al xatbot en 3 passos clicant aquí (Enllaç extern).
